[client]
showSidebarNavigation = false
toolbarMode = "minimal"

[theme]
primaryColor = "#7C3AED"
backgroundColor = "#07080F"
secondaryBackgroundColor = "#06020C"
textColor = "#F8FAFC"
font = "sans serif"

[runner]
fastReruns = true
